<?php
return array (
  'SITE_NAME' => 'thinkphpcms',
  'SITE_URL' => 'http://www.thinkphpcms.com',
  'SITE_LOGO' => '/Uploads/System/Logo/58c5f1c6df1eb.jpg',
  'SITE_ICO' => '',
  'SITE_TELPHONE' => '0755-8888-8888',
  'SITE_PHONE' => '15013721945',
  'SITE_FAX' => '4548521032',
  'SITE_EMAIL' => 'postmaster@szqcmaker.com',
  'SITE_CR' => '版权所有：2016-2026 启航创客教育',
  'SITE_ADDRESS' => '深圳市龙华新区明治街道上塘综路722室',
  'SITE_AUTHER' => '其他信息',
  'SITE_TITLE' => '创客教育',
  'SITE_KEYWORDS' => '关键字，关键字2',
  'SITE_DESCRIPTION' => '网站描述',
  'FILE_SIZE' => '2097152',
  'FILE_TYPE' => 'jpg|png|jpeg|rar|zip|doc|docx|gif|ppt|xsl|txt|mp3|mp4|avi',
  'WATE_OPEN' => '2',
  'WATE_TYPE' => '1',
  'WATE_POSITION' => '1',
  'WATE_THUMB' => '',
  'WATE_CONTENT' => '',
  'CODE_HEAD' => '&lt;script&gt;console.log(&quot;header&quot;);&lt;/script&gt;',
  'CODE_BODY' => '&lt;script&gt;console.log(&quot;footer&quot;);&lt;/script&gt;',
  'HTML_FILE_SUFFIX' => '.html',
  'WATE_ADD_WAY' => '3',
);