<?php
return array (
  'SITE_NAME' => 'thinkphpcms',
  'SITE_URL' => 'http://www.thinkphpcms.com',
  'SITE_LOGO' => '/Uploads/System/Logo/58bf9f06606a4.gif',
  'SITE_ICO' => '/Uploads/System/Ico/58bf9f08d13e1.ico',
  'SITE_TELPHONE' => '0795-49856133',
  'SITE_PHONE' => '15013721945',
  'SITE_FAX' => '4548521032',
  'SITE_EMAIL' => '848464730@qq.com',
  'SITE_CR' => '2017 © THINKPHPCMS.com',
  'SITE_ADDRESS' => '大兴路45号',
  'SITE_AUTHER' => '其他信息',
  'SITE_TITLE' => '标题',
  'SITE_KEYWORDS' => '关键字，关键字2',
  'SITE_DESCRIPTION' => '网站描述',
  'FILE_SIZE' => '2097152',
  'FILE_TYPE' => 'jpg|png|jpeg|rar|zip|doc|docx|gif|ppt|xsl|txt|mp3|mp4|avi',
  'WATE_OPEN' => '2',
  'WATE_TYPE' => '1',
  'WATE_POSITION' => '1',
  'WATE_THUMB' => '',
  'WATE_CONTENT' => '',
  'CODE_HEAD' => '&lt;script&gt;console.log(&quot;header&quot;);&lt;/script&gt;',
  'CODE_BODY' => '&lt;script&gt;console.log(&quot;footer&quot;);&lt;/script&gt;',
  'WATE_ADD_WAY' => '3',
);