<?php
return array (
  'SITE_NAME' => '金融网站',
  'SITE_URL' => 'http://www.jinrong.com',
  'SITE_LOGO' => '/Uploads/System/Logo/58fef4d504d93.jpg',
  'SITE_ICO' => '',
  'SITE_TELPHONE' => '0755-8888-8888',
  'SITE_PHONE' => '88888888',
  'SITE_FAX' => '88888888',
  'SITE_EMAIL' => '88888888',
  'SITE_CR' => '&lt;p style=&quot;text-align: center;&quot;&gt;&lt;span&gt;Copyright &amp;copy; 2017 | &amp;nbsp;深圳 版权所有 | &lt;a href=&quot;http://www.miitbeian.gov.cn/state/outPortal/loginPortal.action&quot; target=&quot;_blank&quot;&gt;&lt;span style=&quot;color:#ffffff;&quot;&gt;粤ICP备：号&lt;/span&gt;&lt;/a&gt;         &lt;/span&gt;       &lt;/p&gt;',
  'SITE_ADDRESS' => '',
  'SITE_AUTHER' => '',
  'SITE_TITLE' => '金融',
  'SITE_KEYWORDS' => '关键字，关键字2',
  'SITE_DESCRIPTION' => '网站描述',
  'FILE_SIZE' => '2097152',
  'FILE_TYPE' => 'jpg|png|jpeg|rar|zip|doc|docx|gif|ppt|xsl|txt|mp3|mp4|avi',
  'WATE_OPEN' => '2',
  'WATE_TYPE' => '1',
  'WATE_POSITION' => '1',
  'WATE_THUMB' => '',
  'WATE_CONTENT' => '',
  'CODE_HEAD' => '',
  'CODE_BODY' => '',
  'HTML_CACHE_ON' => 'true',
  'HTML_FILE_SUFFIX' => '.html',
  'WATE_ADD_WAY' => '3',
);